version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  disable:
    - errcheck

linters-settings:
  staticcheck:
    checks: ["all"]

issues:
  exclude-dirs:
    - vendor
